spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mail:


    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        debug: true
        smtp:
          auth:
          starttls:
            enable: true
      debug: true

logging:
  level:
    org:
      springframework:
        security: DEBUG
base:
  url: https://testpool-app-3g73f.ondigitalocean.app/testpool-fe/index.html#/

myapp:
  maxPoints: 10
  maxQuestions: 10


